services:
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_db
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    networks:
      - backend
    depends_on:
      - db
  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: test_db
    depends_on:
      - db
    networks:
      - backend
    ports:
      - "3000:3000"
    container_name: backend
  frontend:
    build: ./frontend
    networks:
      - frontend
    ports:
      - "5173:5000"
    container_name: frontend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
