services:
  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "${MACHINE_PORTAINER_PORT:-9000}:${PORTAINER_PORT:-9000}"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - public
  uptimkuma:
    image: louislam/uptime-kuma:latest
    environment:
      - TZ=Europe/Paris
    volumes:
      - uptime_kuma_data:/app/data
    ports:
      - "${MACHINE_KUMA_PORT:-3001}:${KUMA_PORT:-3001}"
    networks:
      - public
      - private
    depends_on:
      - backend
      - frontend
      - db
    restart: always

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
    secrets:
      - mysql_root_password
      - mysql_database
      - mysql_user
      - mysql_user_password
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - private

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    secrets:
      - mysql_root_password
    deploy:
      replicas: 0
      restart_policy:
        condition: on-failure
    ports:
      - "${MACHINE_PHPMYADMIN_PORT:-80}:${PHPMYADMIN_PORT:-80}"
    networks:
      - private
    depends_on:
      - db

  backend:
    image: backend-node
    environment:
      DB_HOST: db
      DB_USER_FILE: /run/secrets/mysql_user
      DB_PASSWORD_FILE: /run/secrets/mysql_user_password
      DB_NAME_FILE: /run/secrets/mysql_database
      ALLOWED_ORIGINS: ${HOST:-http://localhost}:${MACHINE_FRONTEND_PORT:-5173}
      BACKEND_PORT: ${BACKEND_PORT:-3000}
    secrets:
      - mysql_user
      - mysql_user_password
      - mysql_database
    healthcheck:
      test: [ "CMD", "sh", "-c", "curl -f ${HOST:-http://localhost}:${BACKEND_PORT:-3000}/health" ]
      interval: 5s
      timeout: 3s
      retries: 3
    depends_on:
      - db
    networks:
      - private
      - public
    ports:
      - "${MACHINE_BACKEND_PORT:-3000}:${BACKEND_PORT:-3000}"

  frontend:
    image: frontend-vue
    environment:
      VITE_API_URL: ${HOST:-http://localhost}:${BACKEND_PORT:-3000}
      VITE_PORT: ${FRONTEND_PORT:-5173}
    networks:
      - public
    ports:
      - "${MACHINE_FRONTEND_PORT:-5173}:${FRONTEND_PORT:-5173}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "${HOST:-http://localhost}:${FRONTEND_PORT:-5173}" ]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  portainer_data:
    driver: local
  uptime_kuma_data:
    driver: local

secrets:
  mysql_root_password:
    external: true
  mysql_user:
    external: true
  mysql_user_password:
    external: true
  mysql_database:
    external: true

networks:
  private:
    driver: overlay
  public:
    driver: overlay
